<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SHREE" failures="1" tests="1" name="ContactTest" time="29.574" errors="0" timestamp="2024-11-25T11:26:27 IST">
  <testcase classname="testCases.TC_003_ContactTest" name="verify_Contact" time="15.182">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Not Getting Any Confirmation Message expected [Successfully Send Message] but found [No ConfirmationMsg]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Not Getting Any Confirmation Message expected [Successfully Send Message] but found [No ConfirmationMsg]
at testCases.TC_003_ContactTest.verify_Contact(TC_003_ContactTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_Contact -->
</testsuite> <!-- ContactTest -->
